AllCops:
  Exclude:
    - 'bin/**/*'
    - '.irbrc'
    - 'config/**/*'
    - 'config.ru'
    - 'cable/config.ru'
    - 'db/**/*'
    - 'Gemfile'
    - 'spec/**/*'
    - 'vendor/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
  NewCops: enable

require: rubocop-rspec

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20
