version: '3.8'
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.32
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3310:3306'
    volumes:
      - ./mysqlcnf.d:/etc/mysql/conf.d
      - ./tmp/mysql:/var/lib/mysql
  redis:
    image: redis:7.0.9
    ports:
      - '6389:6379'
  api:
    tty: true
    stdin_open: true
    build: .
    command: puma -C config/puma.rb # tail -f /dev/null # bundle exec puma -p 28080 cable/config.ru
    volumes:
      - .:/app
    environment:
      DB_HOST: db
      EDITOR: vim
      BULLET: 1
    ports:
      - "3020:3020"
    depends_on:
      - db
      - redis
