version: '3.8'
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.27
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3310:3306'
    volumes:
      - ./mysqlcnf.d:/etc/mysql/conf.d
      - ./tmp/mysql:/var/lib/mysql
  api:
    tty: true
    stdin_open: true
    build: .
    command: tail -f /dev/null # rails s -b 0.0.0.0
    volumes:
      - .:/app
    environment:
      DB_HOST: db
      EDITOR: vim
      BULLET: 1
    ports:
      - "3010:3000"
    depends_on:
      - db
